# Generated by Django 3.1.7 on 2021-03-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=255, verbose_name='Origin City')),
                ('destination_city', models.CharField(max_length=255, verbose_name='Destination City')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Distance between cities')),
            ],
            options={
                'verbose_name': 'Logistic Network',
                'verbose_name_plural': 'Logistics Network',
                'db_table': 'Logistics Network',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Map Name')),
                ('logistics_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.logisticsnetwork', verbose_name='Logistics Network')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'db_table': 'map',
            },
        ),
    ]
