# Generated by Django 3.1.7 on 2021-03-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='logistics_network',
        ),
        migrations.AddField(
            model_name='logisticsnetwork',
            name='map_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.map', verbose_name='Map'),
        ),
    ]
