# Generated by Django 3.1.7 on 2021-03-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210322_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsnetwork',
            name='map_network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.map', verbose_name='Map'),
            preserve_default=False,
        ),
    ]
