# Generated by Django 3.1.7 on 2021-03-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsnetwork',
            name='distance',
            field=models.CharField(max_length=255, verbose_name='Distance between cities'),
        ),
    ]
