# Generated by Django 3.1.7 on 2021-03-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsnetwork',
            name='destination_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='map.cities', verbose_name='Destination City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticsnetwork',
            name='origin_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='map.cities', verbose_name='Origin City'),
            preserve_default=False,
        ),
    ]
