# Generated by Django 3.1.7 on 2021-03-23 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0007_auto_20210322_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLogisticNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.logisticsnetwork', verbose_name='Logistics Network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
