# Generated by Django 3.1.7 on 2021-03-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_historylogisticnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylogisticnetwork',
            options={'verbose_name': 'Logs Logistic Network', 'verbose_name_plural': 'Logs Logistics Network'},
        ),
        migrations.AlterModelTable(
            name='historylogisticnetwork',
            table='map_logs_logistics_network',
        ),
    ]
